apiVersion: v1
kind: ServiceAccount
metadata:
  name: assumerole
  namespace: assumerole
  labels:
    app.kubernetes.io/name: assumerole
  annotations:
    email: example@example.com
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/eksctl-roxeksctl-addon-iamserviceaccount-sta-Role1-18QP7KDM31YYD
