apiVersion: apps/v1
kind: Deployment
metadata:
  name: assumerole
  namespace: assumerole
  labels:
    app: assumerole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assumerole
  template:
    metadata:
      labels:
        app: assumerole
    spec:
      serviceAccount: assumerole
      containers:
        - name: assumerole
          image: quay.io/cporter/assumerole:1.1000
      securityContext:
        fsGroup: 3001
